import { Pool } from 'pg';
import fs from 'fs';
import path from 'path';
import dotenv from 'dotenv';
import { fileURLToPath } from 'url';

dotenv.config({ path: '.env.local' });

const pool = new Pool({
  connectionString: process.env.DATABASE_URL_UNPOOLED,
  ssl: true,
});

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function migrate() {
  const client = await pool.connect();
  try {
    console.log('Starting migration to Neon DB...');
    
    // Roles must be created outside of a transaction block
    console.log('Ensuring roles exist...');
    await client.query(`
      DO $$
      BEGIN
        IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'authenticated') THEN
          CREATE ROLE authenticated NOLOGIN;
        END IF;
        IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'anon') THEN
          CREATE ROLE anon NOLOGIN;
        END IF;
        IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'service_role') THEN
          CREATE ROLE service_role NOLOGIN;
        END IF;
        IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'project_admin') THEN
          CREATE ROLE project_admin NOLOGIN;
        END IF;
      END
      $$;
    `);

    await client.query('BEGIN');

    console.log('Resetting schemas...');
    await client.query(`
      DROP SCHEMA IF EXISTS public CASCADE;
      CREATE SCHEMA public;
      GRANT ALL ON SCHEMA public TO public;
      
      DROP SCHEMA IF EXISTS auth CASCADE;
      DROP SCHEMA IF EXISTS realtime CASCADE;
      DROP SCHEMA IF EXISTS storage CASCADE;
      DROP SCHEMA IF EXISTS system CASCADE;
    `);

    console.log('Creating auth, realtime, and storage schemas/functions...');
    await client.query(`
      CREATE SCHEMA IF NOT EXISTS auth;
      
      CREATE TABLE IF NOT EXISTS auth.users (
        id uuid PRIMARY KEY,
        email text,
        created_at timestamptz DEFAULT clock_timestamp()
      );
      
      CREATE OR REPLACE FUNCTION auth.uid() RETURNS uuid AS $$
        SELECT nullif(current_setting('request.jwt.claims', true)::jsonb->>'sub', '')::uuid;
      $$ LANGUAGE SQL STABLE;
      
      CREATE OR REPLACE FUNCTION auth.jwt() RETURNS jsonb AS $$
        SELECT nullif(current_setting('request.jwt.claims', true), '')::jsonb;
      $$ LANGUAGE SQL STABLE;

      CREATE SCHEMA IF NOT EXISTS realtime;
      CREATE TABLE IF NOT EXISTS realtime.channels (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        pattern text NOT NULL UNIQUE,
        description text,
        enabled boolean DEFAULT true
      );
      CREATE TABLE IF NOT EXISTS realtime.messages (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        channel text NOT NULL,
        event text NOT NULL,
        payload jsonb NOT NULL,
        created_at timestamptz DEFAULT clock_timestamp()
      );
      CREATE OR REPLACE FUNCTION realtime.publish(channel text, event text, payload jsonb) RETURNS void AS $$
      BEGIN
        PERFORM pg_notify(channel, json_build_object('event', event, 'payload', payload)::text);
      END;
      $$ LANGUAGE plpgsql;

      CREATE OR REPLACE FUNCTION realtime.channel_name() RETURNS text AS $$
        SELECT current_setting('realtime.channel_name', true);
      $$ LANGUAGE SQL STABLE;

      CREATE SCHEMA IF NOT EXISTS storage;
      CREATE OR REPLACE FUNCTION storage.foldername(name text) RETURNS text[] AS $$
        SELECT string_to_array(name, '/');
      $$ LANGUAGE SQL IMMUTABLE;
      CREATE TABLE IF NOT EXISTS storage.objects (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        bucket_id text,
        bucket text,
        name text,
        key text,
        owner uuid,
        created_at timestamptz DEFAULT clock_timestamp(),
        updated_at timestamptz DEFAULT clock_timestamp(),
        last_accessed_at timestamptz DEFAULT clock_timestamp(),
        metadata jsonb,
        path_tokens text[] GENERATED ALWAYS AS (string_to_array(name, '/')) STORED,
        owner_id text,
        version text,
        uploaded_by text
      );

      CREATE SCHEMA IF NOT EXISTS system;
      CREATE OR REPLACE FUNCTION system.update_updated_at() RETURNS trigger AS $$
      BEGIN
        NEW.updated_at = clock_timestamp();
        RETURN NEW;
      END;
      $$ LANGUAGE plpgsql;
    `);

    console.log('Applying whappi-core.sql...');
    const schemaPath = path.join(__dirname, '..', '20260820062819_whappi-core.sql');
    let schemaSql = fs.readFileSync(schemaPath, 'utf8');

    await client.query(schemaSql);

    await client.query('COMMIT');
    console.log('Migration completed successfully!');
  } catch (err) {
    await client.query('ROLLBACK');
    console.error('Migration failed:', err);
  } finally {
    client.release();
    await pool.end();
  }
}

migrate();
